feat: add net.env.in for network interface configuration

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,18 +1,18 @@
 #!/bin/sh
 
 error() {
-    printf "\033[31;1m%s\033[0m\n" "$@"
-    exit 1
+	printf "\033[31;1m%s\033[0m\n" "$@"
+	exit 1
 }
 
 healthy_breakup() {
-    printf "\033[32;1m%s\033[0m\n" "$@"
-    exit 0
+	printf "\033[32;1m%s\033[0m\n" "$@"
+	exit 0
 }
 
 prompt_user() {
-    printf "%s" "$1" >&2
-    read -r "$2"
+	printf "%s" "$1" >&2
+	read -r "$2"
 }
 
 # switch to update as default
@@ -24,25 +24,25 @@ INTERACTIVE=yes
 [ "$1" = "no_manual_setup" ] && INTERACTIVE=no
 
 if [ "$INTERACTIVE" = "yes" ]; then
-    # sets REMAKE_ENVIRONMENT to yes if any one of these is true
-    #       1. shared.env doesnt exist
-    #       2. Offline/AA2/aa2.env doesnt exist
-    #       3. there is an "(environment)" in the commit message
-    #       4. the user answers "y" to the query
-    (
-	! test -e shared.env \
-	    || ! test -e Offline/AA2/aa2.env \
-	    || git log --format=%B -n 1 | head -n 1 | grep "(environment)" > /dev/null \
-	    || (
-		prompt_user "Do you wish to manually reconfigure your configuration files? (N/y): " WISH ;
-		[ "$WISH" = "y" ]
-	    )
-    ) \
-	&& REMAKE_ENVIRONMENT="yes" \
-	&& (
-	    cp shared.env.in shared.env
-	    cp Offline/AA2/aa2.env.in Offline/AA2/aa2.env
-	)
+	# sets REMAKE_ENVIRONMENT to yes if any one of these is true
+	#       1. shared.env doesnt exist
+	#       2. Offline/AA2/aa2.env doesnt exist
+	#       3. there is an "(environment)" in the commit message
+	#       4. the user answers "y" to the query
+	(
+		! test -e shared.env ||
+			! test -e Offline/AA2/aa2.env ||
+			git log --format=%B -n 1 | head -n 1 | grep "(environment)" >/dev/null ||
+			(
+				prompt_user "Do you wish to manually reconfigure your configuration files? (N/y): " WISH
+				[ "$WISH" = "y" ]
+			)
+	) &&
+		REMAKE_ENVIRONMENT="yes" &&
+		(
+			cp shared.env.in shared.env
+			cp Offline/AA2/aa2.env.in Offline/AA2/aa2.env
+		)
 fi
 
 test -e database || mkdir database
@@ -53,36 +53,51 @@ test -e database/sig-device-operation || mkfifo database/sig-device-operation
 
 # easier to add scripts
 install_script() {
-    echo "Installing $1..."
+	echo "Installing $1..."
 
-    (
-	mkdir -p "/usr/local/bin/"
-	sed 's;\(MYTEMPO_DATA=\);\1'"$(realpath .);" System/"$1" > "/usr/local/bin/$1" \
-	    && chmod +x "/usr/local/bin/$1" \
-	    && systemctl link ./System/systemd/system/"$1".service
-    ) || error "Could not install $1, check your perms"
+	(
+		mkdir -p "/usr/local/bin/"
+		sed 's;\(MYTEMPO_DATA=\);\1'"$(realpath .);" System/"$1" >"/usr/local/bin/$1" &&
+			chmod +x "/usr/local/bin/$1" &&
+			systemctl link ./System/systemd/system/"$1".service
+	) || error "Could not install $1, check your perms"
 }
 
 install_script chancelor
 install_script provost
 
 if [ "$UPDATING" = "no" ]; then
-    echo "Disabling USB autosuspend (see #3)"
+	echo "Disabling USB autosuspend (see #3)"
 
-    (
-	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*$/GRUB_CMDLINE_LINUX_DEFAULT="usbcore.autosuspend=-1 loglevel=3 quiet"/' /etc/default/grub \
-	    && grub-mkconfig -o /boot/grub/grub.cfg
-    ) || error "Could not disable USB autosuspend feature"
+	(
+		sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*$/GRUB_CMDLINE_LINUX_DEFAULT="usbcore.autosuspend=-1 loglevel=3 quiet"/' /etc/default/grub &&
+			grub-mkconfig -o /boot/grub/grub.cfg
+	) || error "Could not disable USB autosuspend feature"
 
-    echo "Speeding up boot process"
+	echo "Speeding up boot process"
 
-    (
-	systemctl disable systemd-networkd-wait-online.service \
-	    && systemctl enable NetworkManager-wait-online.service
-    ) || error "Could not switch network configuration method"
+	(
+		systemctl disable systemd-networkd-wait-online.service &&
+			systemctl enable NetworkManager-wait-online.service
+	) || error "Could not switch network configuration method"
 fi
 
 ./build || error "Error while rebuilding the codebase, please file an issue at https://github.com/MyTempoESP/MonoTempo/issues/new?template=BLANK_ISSUE"
+
+if ! [ -e "Net/net.env" ]; then
+
+	echo "Setting up Net/net.env"
+
+	cp Net/net.env.in Net/net.env
+
+	DEV=$(nmcli -g "" -f GENERAL.DEVICE,GENERAL.PRODUCT d show | grep "Android" -B 1 | head -n 1)
+
+	if [ -z "$DEV" ]; then
+		sed -i 's/LTE4G_IFACE=.*$/LTE4G_IFACE='"$DEV"'/' Net/net.env
+	else
+		printf "\033[31;1m%s\033[0m\n" "No 4G modem detected, skipping Net/net.env setup"
+	fi
+fi
 
 # if does not remake env, die
 [ "$REMAKE_ENVIRONMENT" = "no" ] && healthy_breakup "All done! Please reboot for the changes to take effect."
@@ -92,15 +107,15 @@ prompt_user "Type the device's reader type (impinj/chafon): " READER_TYPE
 prompt_user "Is your Arduino screen programmer detected as ACM or USB? (leave blank if you dont know): " SCREEN_PATH
 
 echo "Setting up hostname"
-(echo "my$DEVICE_ID" > /etc/hostname) || error "Could not set machine hostname"
+(echo "my$DEVICE_ID" >/etc/hostname) || error "Could not set machine hostname"
 
 echo "Setting up shared.env"
 
 (
-    sed -i "s/MYTEMPO_READER_TYPE=.*$/MYTEMPO_READER_TYPE=$READER_TYPE/" shared.env \
-	&& sed -i "s/MYTEMPO_READER=.*$/MYTEMPO_READER=PORTAL LEITOR RFIDMY${DEVICE_ID:-501}/" shared.env \
-	&& sed -i "s/MYTEMPO_EQUIP=.*$/MYTEMPO_EQUIP=PORTAL LEITOR RFIDMY${DEVICE_ID:-501}/" shared.env \
-	&& sed -i "s/MYTEMPO_DEVID=.*$/MYTEMPO_DEVID=${DEVICE_ID:-501}/" shared.env
+	sed -i "s/MYTEMPO_READER_TYPE=.*$/MYTEMPO_READER_TYPE=$READER_TYPE/" shared.env &&
+		sed -i "s/MYTEMPO_READER=.*$/MYTEMPO_READER=PORTAL LEITOR RFIDMY${DEVICE_ID:-501}/" shared.env &&
+		sed -i "s/MYTEMPO_EQUIP=.*$/MYTEMPO_EQUIP=PORTAL LEITOR RFIDMY${DEVICE_ID:-501}/" shared.env &&
+		sed -i "s/MYTEMPO_DEVID=.*$/MYTEMPO_DEVID=${DEVICE_ID:-501}/" shared.env
 ) || error "Could not setup shared.env"
 
 echo "Setting up Offline/AA2/aa2.env"
@@ -110,19 +125,19 @@ READER_NAME=
 [ "$READER_TYPE" = "impinj" ] && READER_NAME=ff
 
 (
-    sed -i "s/READER_NAME=.*$/READER_NAME=$READER_NAME/" Offline/AA2/aa2.env \
-	&& sed -i "s;READER_PATH=.*$;READER_PATH=/dev/tty${SCREEN_PATH:-USB}0;" Offline/AA2/aa2.env
+	sed -i "s/READER_NAME=.*$/READER_NAME=$READER_NAME/" Offline/AA2/aa2.env &&
+		sed -i "s;READER_PATH=.*$;READER_PATH=/dev/tty${SCREEN_PATH:-USB}0;" Offline/AA2/aa2.env
 ) || error "Something went wrong with the setup, i'm not really a sed expert"
 
 echo "Setting reader ip"
 
 if [ "$READER_TYPE" = "chafon" ]; then
-    sed -i "s/READER_IP=.*$/READER_IP=192.168.1.200/" shared.env || error "Error setting reader IP address"
+	sed -i "s/READER_IP=.*$/READER_IP=192.168.1.200/" shared.env || error "Error setting reader IP address"
 fi
 
 if [ "$READER_TYPE" = "impinj" ]; then
-    prompt_user "Type the reader IP address: " READER_IP
-    sed -i "s/READER_IP=.*$/READER_IP=$READER_IP/" shared.env || error "Error setting reader IP address"
+	prompt_user "Type the reader IP address: " READER_IP
+	sed -i "s/READER_IP=.*$/READER_IP=$READER_IP/" shared.env || error "Error setting reader IP address"
 fi
 
 healthy_breakup "All done! Please reboot for the changes to take effect."
