[fix]: group ./build cmd and || error
this is needed so error doesnt trigger when update is 'no'

diff --git a/install b/install
--- a/install
+++ b/install
@@ -55,8 +55,10 @@ if [ "$UPDATING" = "no" ]; then
 fi
 
 [ "$UPDATING" = "yes" ] \
-    && ./build \
-	|| error "Error while rebuilding the codebase, please file an issue at https://github.com/MyTempoESP/MonoTempo/issues/new?template=BLANK_ISSUE"
+	&& \
+	(
+	./build || error "Error while rebuilding the codebase, please file an issue at https://github.com/MyTempoESP/MonoTempo/issues/new?template=BLANK_ISSUE"
+)
 
 read -p "Do you wish to manually setup your configuration files? (N/y): " WISH
 
